name: CI - Lint, Test, Build & Docker Build

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  backend:
    name: Backend - Lint, Test & Build
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: companyhub_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U test"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        working-directory: backend
        run: pnpm install

      - name: Generate Prisma Client
        working-directory: backend
        run: pnpm prisma:generate

      - name: Apply migrations
        working-directory: backend
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/companyhub_test
        run: pnpm prisma migrate deploy

      - name: Lint
        working-directory: backend
        run: pnpm lint

      - name: Test
        working-directory: backend
        env:
          DATABASE_URL: postgresql://test:test@localhost:5432/companyhub_test
        run: pnpm test -- --runInBand

      - name: Build
        working-directory: backend
        run: pnpm build

      - name: Docker Build (backend)
        run: docker build -t companyhub-backend ./backend

  frontend:
    name: Frontend - Lint, Test & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "pnpm"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        working-directory: frontend
        run: pnpm install

      - name: Lint
        working-directory: frontend
        run: pnpm lint

      - name: Test
        working-directory: frontend
        run: pnpm test -- --watchAll=false

      - name: Build
        working-directory: frontend
        run: pnpm build

      - name: Docker Build (frontend)
        run: docker build -t companyhub-frontend ./frontend
